# Generated by Django 6.0.6 on 2026-06-17 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "jb_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("job", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "pr_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("project_name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "st_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name="users",
            old_name="st_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="is_verivied",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="st_lastname",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="st_name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="users",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="phone",
            field=models.CharField(default="", max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="salary",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "dp_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("dp_name", models.CharField(max_length=50)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="users",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="acounts.department",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="acounts.jobs",
            ),
        ),
        migrations.CreateModel(
            name="Project_assignment",
            fields=[
                (
                    "assignment_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("assignment_date", models.DateField()),
                ("role", models.CharField(max_length=50)),
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acounts.projects",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Daily_work_report",
            fields=[
                (
                    "report_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("reports_date", models.DateField()),
                ("hours_worked", models.DecimalField(decimal_places=2, max_digits=5)),
                ("work_description", models.TextField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acounts.project_assignment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projects",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="acounts.status",
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "task_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("task_name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("created_date", models.DateField()),
                ("status", models.CharField(max_length=50)),
                ("due_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acounts.projects",
                    ),
                ),
            ],
        ),
    ]
