# Generated by Django 6.0.6 on 2026-06-18 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acounts", "0002_jobs_projects_status_rename_st_id_users_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="manager",
        ),
    ]
