# Generated by Django 6.0.6 on 2026-06-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acounts", "0003_remove_department_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="hire_date",
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
