# Generated by Django 6.0.6 on 2026-06-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acounts", "0004_alter_users_hire_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="hire_date",
        ),
    ]
