# Generated by Django 6.0.6 on 2026-06-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acounts", "0005_remove_users_hire_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="hire_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
